cmake_minimum_required(VERSION 3.16)

# Parse the real, patched wrapper without configuring the Android toolchain.
# Only build-graph commands are stubbed; CMake itself validates the syntax.
if(NOT DEFINED WRAPPER_FILE OR NOT EXISTS "${WRAPPER_FILE}")
    message(FATAL_ERROR "Pass -DWRAPPER_FILE=<patched wrappers/java/CMakeLists.txt>")
endif()

macro(project)
endmacro()
macro(add_generate_swig_target)
endmacro()
macro(set_source_files_properties)
endmacro()
macro(add_custom_target)
endmacro()
macro(add_dependencies)
endmacro()
macro(target_compile_definitions)
endmacro()
macro(target_include_directories)
endmacro()
macro(target_link_libraries)
endmacro()

macro(add_library target)
    if("${target}" STREQUAL "OsmAndCoreJNI" OR "${target}" STREQUAL "OsmAndCoreWithJNI")
        set(sources ${ARGN})
        list(FIND sources "FlightVectorLineBridge.cpp" bridge_index)
        if(bridge_index LESS 0)
            message(FATAL_ERROR "${target} does not include FlightVectorLineBridge.cpp")
        endif()
        set(checked_${target} TRUE)
    endif()
endmacro()

set(CMAKE_TARGET_OS android)
include("${WRAPPER_FILE}")
if(NOT checked_OsmAndCoreJNI OR NOT checked_OsmAndCoreWithJNI)
    message(FATAL_ERROR "Both JNI library declarations must be checked")
endif()
message(STATUS "Patched JNI CMake syntax and flight bridge sources: OK")
